services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - ./awslocal:/etc/localstack/init/ready.d/
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/Caddyfile
    ports:
      - "8069:8069"
    command: caddy  run --config /Caddyfile
